version: '3.8'

services:
  db:
    image: postgres
    container_name: database-oms-tmb
    restart: always
    networks:
      - apitmb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2604
      POSTGRES_DB: ApiTMB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api-oms-tmb
    restart: always
    networks:
      - apitmb
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ApiTMB;Username=admin;Password=2604
      - APPLY_MIGRATION=true
    depends_on:
      - db
volumes:
  pgdata:

networks:
    apitmb:
        name: "Api TMB"
        driver: bridge